# wrangler.toml
name = 'guide-book'
main = "workers/worker.js"
compatibility_date = "2025-11-12"
workers_dev = false

assets = { directory = "dist/spa", binding = "ASSETS" }

[[routes]]
pattern = "guides.sirrus.cc"
custom_domain = true